ModelE/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events do
  	resources :attendees, :controller => "event_attendees" 
  end
end

ModelE/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ModelE/app/models/attendee.rb
class Attendee < ApplicationRecord
	validates_presence_of :name

	belongs_to :event
end

ModelE/app/models/category.rb
class Category < ApplicationRecord
	has_many :event
end

ModelE/app/models/event.rb
class Event < ApplicationRecord
	has_many :event_groupships
	has_many :groups, :through => :event_groupships


	has_one :location

	has_many :attendees

	belongs_to :category
end

ModelE/app/models/event_groupship.rb
class EventGroupship < ApplicationRecord
	belongs_to :event
	belongs_to :group
end

ModelE/app/models/group.rb
class Group < ApplicationRecord
	has_many :event_groupships
	has_many :events, :through => :event_groupships
end

ModelE/app/models/location.rb
class Location < ApplicationRecord
	belongs_to :event

end

ModelE/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

ModelE/app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController

	before_action :find_event

	def index
		byebug
		@attendees = @event.attendees
	end
	def new
		@attendee =  @event.attendees.new
	end
	def create
		@attendee =  @event.attendees.new(attendee_params)
		if @attendee.save
			flash[:notice] = "新增成功"
			redirect_to :action => :index
		else
			render :action => :new
		end
	end
	def show
		
	end
	def edit
		
	end
	def update
		
	end
	def destroy
		
	end

	private
	def attendee_params
		params.require(:attendee).permit(:name)
	end

	def find_event
		@event = Event.find(params[:event_id])
	end
end

ModelE/app/controllers/events_controller.rb
class EventsController < ApplicationController
	def index
		@events = Event.all
	end
end

ModelE/app/helpers/application_helper.rb
module ApplicationHelper
end

ModelE/app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

ModelE/app/helpers/events_helper.rb
module EventsHelper
end

ModelE/app/views/event_attendees/index.html.erb
<ul>
<% @attendees.each do |a| %>
<li><%= a.name %></li>
<% end %>	
</ul>


<%= link_to "New attendee", new_event_attendee_path(@event),  :class => "btn btn-success" %>
<%= link_to "Index(events)", events_path , :class => "btn btn-default" %>

ModelE/app/views/event_attendees/new.html.erb
<%= form_for @attendee, :url => event_attendees_path(@event) do |f|%>
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, :class=>"form-control"%>
	</div>
	<div class="form-group">
	<%= f.submit %>
	</div>
<% end %>

ModelE/app/views/events/index.html.erb
<ul>
<% @events.each do |e|%>
<li>
<%= e.name %>
<%= link_to "show_attendees" , event_attendees_path(e), :class=>"btn btn-primery"%>
</li>
<% end %>
	
</ul>

ModelE/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ModelE</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>	
  	<%= flash[:notice]%>
    <%= yield %>
  </body>
</html>